name: lab-environment
channels:
  - conda-forge
dependencies:
  - python >=3.10,<3.13
  - numpy >=1.23.0,<2.0.0
  - tensorflow >=2.5,<2.17
  - tensorflow-probability >=0.13,<0.25
  - notebook
  - matplotlib
  - taskipy
  - pip
  - pip:
    - trieste >=4.2
